using alltdl.Constants;

using System.Linq;
using System.Text.RegularExpressions;

namespace alltdl.Utils
{
    /// <summary>
    /// The string helper.
    /// </summary>
    public static class StringHelper
    {
        public static bool HasEmbeddedSpaces(this string s)
        {
            return s.Trim().Any(ch => ch == ' ');
        }

        /// <summary>
        /// Determines whether [is valid URL] [the specified URL].
        /// </summary>
        /// <param name="url">The URL.</param>
        /// <returns>
        ///   <c>true</c> if [is valid URL] [the specified URL]; otherwise, <c>false</c>.
        /// </returns>
        /// <autogeneratedoc />
        public static bool IsValidUrl(string url)
        {
            var rgx = new Regex(RegexPattern.Url, RegexOptions.Compiled | RegexOptions.IgnoreCase);
            return rgx.IsMatch(url);
        }

        /// <summary>
        /// Checks if a string start with a lower case.
        /// </summary>
        /// <param name="s">The string.</param>
        /// <returns></returns>
        /// <review />
        public static bool StartsWithLower(this string s)
        {
            return !string.IsNullOrWhiteSpace(s) && char.IsLower(s[0]);
        }

        /// <summary>
        /// Checks if a string starts with an upper case.
        /// </summary>
        /// <param name="s">The string.</param>
        /// <returns></returns>
        public static bool StartsWithUpper(this string s)
        {
            return !string.IsNullOrWhiteSpace(s) && char.IsUpper(s[0]);
        }
    }
}